### ISSUE TITLE
npm ERR! Failed at the rtl@0.12.3-beta postinstall script.

### ISSUE THREAD

**Issue by AngeloMetal** [Ride-The-Lightning/RTL#1040]
**Describe the bug**
I've cloned RTL and try to install it with npm. Specifically, with ``npm install --only=prod``. This is what I get:
```
bitcoin@raspibolt:~/RTL $ npm install --only=prod
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN tarball tarball data for material-design-icons@3.0.1 (sha1-mnHEh0chjrylHlGmbaaCA4zct78=) seems to be corrupted. Trying one more time.

> @fortawesome/fontawesome-common-types@0.2.36 postinstall /home/bitcoin/RTL/node_modules/@fortawesome/fontawesome-common-types
> node attribution.js

Font Awesome Free 0.2.36 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)


> @fortawesome/fontawesome-svg-core@1.2.36 postinstall /home/bitcoin/RTL/node_modules/@fortawesome/fontawesome-svg-core
> node attribution.js

Font Awesome Free 1.2.36 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)


> @fortawesome/free-regular-svg-icons@5.15.4 postinstall /home/bitcoin/RTL/node_modules/@fortawesome/free-regular-svg-icons
> node attribution.js

Font Awesome Free 5.15.4 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)


> @fortawesome/free-solid-svg-icons@5.15.4 postinstall /home/bitcoin/RTL/node_modules/@fortawesome/free-solid-svg-icons
> node attribution.js

Font Awesome Free 5.15.4 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)


> rtl@0.12.3-beta postinstall /home/bitcoin/RTL
> ngcc

/home/bitcoin/RTL/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:3
      import {createRequire as __cjsCompatRequire} from 'module';
             ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rtl@0.12.3-beta postinstall: `ngcc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rtl@0.12.3-beta postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bitcoin/.npm/_logs/2022-06-14T11_01_38_756Z-debug.log
```
I have tried to follow [some stackoverflow answers](https://stackoverflow.com/questions/42308879/how-to-solve-npm-error-npm-err-code-elifecycle?page=1&tab=scoredesc#tab-top), but none of those fixed it. 

**Your environment**
* Version of `RTL`: Latest, at the moment v0.12.3. 
* Version of `core lightning`: v0.10.2
* Version of `bitcoind`: 22.0
* Operating system (`uname -a` on *Nix): Linux raspibolt 5.10.103-v7l+

**Comment by ShahanaFarooqui** [comment]
What NodeJS and npm versions are you on?

**Comment by ShahanaFarooqui** [comment]
Can you retry the first SO answer with ‘npm install —prod —legacy-peer-does. 

Try this only if your NodeJS version is >= 12. RTL can’t run on NodeJS’s lesser than 12 version.

**Comment by ShahanaFarooqui** [comment]
@AngeloMetal I usually do not recommend ‘npm cache clean —force’. So please feel free to skip to step 2 directly.

**Comment by AngeloMetal** [comment]
> What NodeJS and npm versions are you on?
npm v6.7.0
node v11.15.0

> RTL can’t run on NodeJS’s lesser than 12 version.
Alright, I'll upgrade and let you know.

**Comment by AngeloMetal** [comment]
So, I upgraded to v14.16.1, and this is what I get now:
```
bitcoin@raspibolt:~/RTL $ npm install --only=prod
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bitcoin/.npm/_logs/2022-06-14T17_05_01_999Z-debug.log
```

**Comment by ShahanaFarooqui** [comment]
Npm also needs to be updated to handle lockfileVersion2. The command to update npm is:

npm install npm@latest

**Comment by AngeloMetal** [comment]
Yep, it worked, thank you!

Closed.
