### ISSUE TITLE
{"error":"connect ECONNREFUSED 127.0.0.1:3001"}

### ISSUE THREAD

**Issue by AngeloMetal** [Ride-The-Lightning/RTL#1041]
**Describe the bug**
I tried to access RTL and suddenly, I got this bug that's shown in the screenshot below.
With a ``sudo service RTL status``, I see this:
```
WebSocketServer => Broadcasting error to clients...: {"error":"connect ECONNREFUSED 127.0.0.1:3001"}.
Jun 15 12:10:06 raspibolt node[29121]: [6/15/2022, 12:10:06] INFO: CLWebSocket => Web socket disconnected, will reconnect again....
```

**Screenshots**
https://i.imgur.com/vj87yFh.png

**Your environment**
* Version of `RTL`  v0.12.3.
* Version of `c-lightning` v0.10.2
* Version of `bitcoind` 22.0
* Operating system (`uname -a` on *Nix) Linux raspibolt 5.10.103-v7l+

**Comment by ShahanaFarooqui** [comment]
Which c-lightning-REST version are you on?

**Comment by AngeloMetal** [comment]
> Which c-lightning-REST version are you on?

Release v0.7.2-beta-hotfix (Latest)

**Comment by ShahanaFarooqui** [comment]
Can you please make sure that it is running at 127.0.0.1:3001 because the error message shows that connection is refused from this address.

**Comment by saubyk** [comment]
Hi @AngeloMetal can you please confirm, if you are running c-lightning-REST? And what port is it running on?

**Comment by AngeloMetal** [comment]
> Hi @AngeloMetal can you please confirm, if you are running c-lightning-REST? And what port is it running on?

I confirm it has stopped working. I was running it on 3001.
```
bitcoin@raspibolt:~/RTL $ sudo journalctl -f -u c-lightning-REST
-- Logs begin at Tue 2022-06-14 13:17:01 BST. --
Jun 15 13:21:50 raspibolt node[4208]:   errno: 'ECONNREFUSED',
Jun 15 13:21:50 raspibolt node[4208]:   code: 'ECONNREFUSED',
Jun 15 13:21:50 raspibolt node[4208]:   syscall: 'connect',
Jun 15 13:21:50 raspibolt node[4208]:   address: '/home/bitcoin/.lightning/bitcoin/lightning-rpc'
Jun 15 13:21:50 raspibolt node[4208]: }
Jun 15 13:21:50 raspibolt systemd[1]: c-lightning-REST.service: Main process exited, code=exited, status=1/FAILURE
Jun 15 13:21:50 raspibolt systemd[1]: c-lightning-REST.service: Failed with result 'exit-code'.
Jun 15 13:22:25 raspibolt systemd[1]: c-lightning-REST.service: Service RestartSec=30s expired, scheduling restart.
Jun 15 13:22:25 raspibolt systemd[1]: c-lightning-REST.service: Scheduled restart job, restart counter is at 1479.
Jun 15 13:22:25 raspibolt systemd[1]: Stopped c-lightning-REST daemon.
Jun 15 13:22:25 raspibolt systemd[1]: Started c-lightning-REST daemon.
Jun 15 13:22:26 raspibolt node[4262]: Reading config file
Jun 15 13:22:26 raspibolt node[4262]: WARN: /home/bitcoin/.lightning/lightning-rpc is missing, using the bitcoin mainnet subdirectory at /home/bitcoin/.lightning/bitcoin instead. error
Jun 15 13:22:27 raspibolt node[4262]: --- Starting the cl-rest server --- warn
Jun 15 13:22:27 raspibolt node[4262]: --- cl-rest api server is ready and listening on port: 3002 --- warn
Jun 15 13:22:27 raspibolt node[4262]: --- cl-rest doc server is ready and listening on port: 4002 --- warn
Jun 15 13:22:27 raspibolt node[4262]: Lightning client connection error error
Jun 15 13:22:27 raspibolt node[4262]: events.js:291
Jun 15 13:22:27 raspibolt node[4262]:       throw er; // Unhandled 'error' event
Jun 15 13:22:27 raspibolt node[4262]:       ^
Jun 15 13:22:27 raspibolt node[4262]: Error: connect ECONNREFUSED /home/bitcoin/.lightning/bitcoin/lightning-rpc
Jun 15 13:22:27 raspibolt node[4262]:     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
Jun 15 13:22:27 raspibolt node[4262]: Emitted 'error' event on LightningClient instance at:
Jun 15 13:22:27 raspibolt node[4262]:     at Socket.<anonymous> (/home/bitcoin/c-lightning-REST/lightning-client-js.js:77:23)
Jun 15 13:22:27 raspibolt node[4262]:     at Socket.emit (events.js:314:20)
Jun 15 13:22:27 raspibolt node[4262]:     at emitErrorNT (internal/streams/destroy.js:92:8)
Jun 15 13:22:27 raspibolt node[4262]:     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
Jun 15 13:22:27 raspibolt node[4262]:     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
Jun 15 13:22:27 raspibolt node[4262]:   errno: 'ECONNREFUSED',
Jun 15 13:22:27 raspibolt node[4262]:   code: 'ECONNREFUSED',
Jun 15 13:22:27 raspibolt node[4262]:   syscall: 'connect',
Jun 15 13:22:27 raspibolt node[4262]:   address: '/home/bitcoin/.lightning/bitcoin/lightning-rpc'
Jun 15 13:22:27 raspibolt node[4262]: }
Jun 15 13:22:27 raspibolt systemd[1]: c-lightning-REST.service: Main process exited, code=exited, status=1/FAILURE
Jun 15 13:22:27 raspibolt systemd[1]: c-lightning-REST.service: Failed with result 'exit-code'.
Jun 15 13:22:57 raspibolt systemd[1]: c-lightning-REST.service: Service RestartSec=30s expired, scheduling restart.
Jun 15 13:22:57 raspibolt systemd[1]: c-lightning-REST.service: Scheduled restart job, restart counter is at 1480.
Jun 15 13:22:57 raspibolt systemd[1]: Stopped c-lightning-REST daemon.
```

**Comment by saubyk** [comment]
So the issues seems to be that C-lIghtning-REST is not able to connect with core lightning. Please confirm if core lightning is running or not?

**Comment by saubyk** [comment]
You can add a config setting for the rpc path in the `cl-rest-config.json` file.
E.g. add LNRPCPATH="/home/<user>/.lightning/testnet" to the config

cl-rest needs to know where the `lightning-rpc` is located for core lightning.
