### ISSUE TITLE
Error for setups running without authentication config params

### ISSUE THREAD

**Issue by ShahanaFarooqui** [Ride-The-Lightning/RTL#1415]
For Umbrel setup, all authentication params are passed via environment. When RTL tries to remove all authentication params, it throws error:

```
file:///RTL/backend/utils/common.js:43
            delete node.authentication.macaroonPath;
                        ^

TypeError: Cannot convert undefined or null to object
    at CommonService.removeAuthSecureData (file:///RTL/backend/utils/common.js:43:25)
    at file:///RTL/backend/utils/common.js:56:46
    at Array.map (<anonymous>)
    at CommonService.removeSecureData (file:///RTL/backend/utils/common.js:56:27)
    at file:///RTL/backend/controllers/shared/RTLConf.js:107:40
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

**Comment by ShahanaFarooqui** [comment]
Closing with PR #1416
