### ISSUE TITLE
[UX branch] Can not start RTL

### ISSUE THREAD

**Issue by MrManPew** [Ride-The-Lightning/RTL#213]
**Describe the bug**
```
admin@rock64:~/download/RTL_UX$ node rtl
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'express'
Require stack:
- /home/admin/download/RTL_UX/app.js
- /home/admin/download/RTL_UX/rtl.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/home/admin/download/RTL_UX/app.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/admin/download/RTL_UX/app.js',
    '/home/admin/download/RTL_UX/rtl.js'
  ]
}
```

The normal branch works well..

**Comment by saubyk** [comment]
Hi @MrManPew did you run `npm install` after pulling the branch?

**Comment by MrManPew** [comment]
I did not know you need to do it after every version... Thanks

**Comment by MrManPew** [comment]
By the way:
```
admin@rock64:~/download/RTL_UX$ npm install
npm WARN @angular/http@7.2.15 requires a peer of @angular/core@7.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@7.2.15 requires a peer of @angular/platform-browser@7.2.15 but none is installed. You must install peer dependencies yourself.

```

**Comment by bolatovumar** [comment]
@MrManPew don't worry about that comment, it's fine.
