### ISSUE TITLE
Failure to start after latest git pull

### ISSUE THREAD

**Issue by MrManPew** [Ride-The-Lightning/RTL#269]
**Describe the bug**
After latest git pull I get this error:
```bash
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'otplib'
Require stack:
- /home/admin/download/RTL/controllers/authenticate.js
- /home/admin/download/RTL/routes/authenticate.js
- /home/admin/download/RTL/app.js
- /home/admin/download/RTL/rtl.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/admin/download/RTL/controllers/authenticate.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/admin/download/RTL/controllers/authenticate.js',
    '/home/admin/download/RTL/routes/authenticate.js',
    '/home/admin/download/RTL/app.js',
    '/home/admin/download/RTL/rtl.js'
  ]
}
```

**Your environment**
* version of `lnd`
`lnd version 0.9.1-beta commit=v0.9.1-beta`
* operating system (`uname -a` on *Nix)
`Linux rock64 4.4.132-1075-rockchip-ayufan-ga83beded8524 #1 SMP Thu Jul 26 08:22:22 UTC 2018 aarch64 GNU/Linux`

**Comment by ShahanaFarooqui** [comment]
@MrManPew Please change your git repository address. Previously it used to be ‘ https://github.com/ShahanaFarooqui/RTL’ but now it has been transferred to ‘ https://github.com/Ride-The-Lightning/RTL’.

**Comment by ShahanaFarooqui** [comment]
We have fixed the issue by deleting the fork from `https://github.com/ShahanaFarooqui/RTL`. Now, it should work as before.

**Comment by MrManPew** [comment]
Great, working, thanks

**Comment by saubyk** [comment]
Closing this ticket.

**Comment by ShahanaFarooqui** [comment]
@MrManPew 
Please change your RTL directory location from `https://github.com/ShahanaFarooqui/RTL` to `https://github.com/Ride-The-Lightning/RTL`, as soon as possible. Otherwise, the code pulled from the old location can break your application, whenever I will try to edit a new PR.

**Comment by MrManPew** [comment]
Great, now it is working. Thanks
