### ISSUE TITLE
"Failed at the rtl@0.8.2-beta postinstall script" during upgrade

### ISSUE THREAD

**Issue by sendbitcoin** [Ride-The-Lightning/RTL#381]
I upgraded from 7.0 to 0.8.2 and got this error, OS is win10:

```
C:\Users\monster\Desktop\rtl2>npm install --only=prod

> rtl@0.8.2-beta postinstall C:\Users\monster\Desktop\rtl2
> ngcc

TypeError: fn(...).finally is not a function
    at AsyncLocker.<anonymous> (C:\Users\monster\Desktop\rtl2\node_modules\@angular\compiler-cli\ngcc\src\locking\async_locker.js:44:63)
    at step (C:\Users\monster\Desktop\rtl2\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\monster\Desktop\rtl2\node_modules\tslib\tslib.js:122:57)
    at fulfilled (C:\Users\monster\Desktop\rtl2\node_modules\tslib\tslib.js:112:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rtl@0.8.2-beta postinstall: `ngcc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rtl@0.8.2-beta postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\monster\AppData\Roaming\npm-cache\_logs\2020-07-14T14_08_51_172Z-debug.log

```

at a glance RTL seems to work and I'm not quiet sure what this postinstall script or ngcc is supposed to do but i thought i let you know as in the past i didnt have and errors during upgrading

I tired fixing it by deleting the lock file or the whole node_modules folder as described here but it's still the same:
https://stackoverflow.com/questions/61122763/another-process-with-id-is-currently-running-ngcc

What exactly has failed here and should i be worried?

**Comment by ShahanaFarooqui** [comment]
@sendbitcoin what are your node and npm versions?

**Comment by sendbitcoin** [comment]
@ShahanaFarooqui after upgrading node i got this:

```

C:\Users\monster\Desktop\rtl2>npm install --only=prod

> rtl@0.8.2-beta postinstall C:\Users\monster\Desktop\rtl2
> ngcc

Another process, with id 8980, is currently running ngcc.
Waiting up to 250s for it to finish.
Error: Timed out waiting 250s for another ngcc process, with id 8980, to complete.
(If you are sure no ngcc process is running then you should delete the lock-file at C:/Users/monster/Desktop/rtl2/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)
    at AsyncLocker.<anonymous> (C:\Users\monster\Desktop\rtl2\node_modules\@angular\compiler-cli\ngcc\src\locking\async_locker.js:91:31)
    at step (C:\Users\monster\Desktop\rtl2\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\monster\Desktop\rtl2\node_modules\tslib\tslib.js:122:57)
    at fulfilled (C:\Users\monster\Desktop\rtl2\node_modules\tslib\tslib.js:112:62)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rtl@0.8.2-beta postinstall: `ngcc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rtl@0.8.2-beta postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\monster\AppData\Roaming\npm-cache\_logs\2020-07-14T14_56_05_622Z-debug.log
```

deleting the lock file and running npm install again seems to gave fixed it as i dont get any more errors now.


did get a couple warnings though:

npm WARN @fortawesome/angular-fontawesome@0.7.0 requires a peer of @angular/core@^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angularx-qrcode@10.0.3 requires a peer of @angular/core@^10.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by ShahanaFarooqui** [comment]
@sendbitcoin these warnings are okay, nothing to worry. Closing the issue now.
