### ISSUE TITLE
Docker Container sets value of key "host" to "localhost" by default rendering the container useless.

### ISSUE THREAD

**Issue by Javihache** [Ride-The-Lightning/RTL#391]
After updating RTL Docker container on a BTCPay Server Docker installation, RTL became inaccessible throwing a 502 Error "Bad Gateway".

Upon further examination of the problem, the old RTL config file in the volume RTL.conf didn't have a "host" entry. The new RTL-Config.json file was set by default to "host": "localhost". This made access to the RTL fail everytime.

**Comment by Eskyee** [comment]
I also had this problem with the latest release with shahanafarooqui/rtl:0.8.2

`Error: Error: Error: ENOTDIR: not a directory, open '/data/RTL.conf/RTL-Config.json'
    at Object.connect.setServerConfiguration (/RTL/connect.js:549:11)
    at Object.<anonymous> (/RTL/rtl.js:6:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Start...config creation at: /data/RTL.conf/RTL-Config.json
Something went wrong while upgrading the RTL config file: 
Error: ENOTDIR: not a directory, open '/data/RTL.conf/RTL-Config.json'
Something went wrong while configuring the node server: 
Error: Error: ENOTDIR: not a directory, open '/data/RTL.conf/RTL-Config.json'
/RTL/connect.js:549
    throw new Error(err);
    ^

Error: Error: Error: ENOTDIR: not a directory, open '/data/RTL.conf/RTL-Config.json'
    at Object.connect.setServerConfiguration (/RTL/connect.js:549:11)
    at Object.<anonymous> (/RTL/rtl.js:6:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)`

**Comment by ShahanaFarooqui** [comment]
From last release onwards, we made ‘host’ configurable too. The host is configurable with environment variable as well as suggested below:

> #### Environment variables
;The environment variable can also be used for all of the above configurations except the UI settings.
;If the environment variables are set, it will take precedence over the parameters in the RTL-Config.json file.
PORT (port number for the rtl node server, default 3000, Required)
HOST (host for the rtl node server, default localhost, Optional)

**Comment by ShahanaFarooqui** [comment]
@Eskyee the RTL config path should be set to ‘/data/’ only NOT ‘/data/RTL.conf/‘.

**Comment by ShahanaFarooqui** [comment]
@Javihache Were you able to access RTL after configuring the 'host' environment variable?

**Comment by Eskyee** [comment]
> @Javihache Were you able to access RTL after configuring the 'host' environment variable?

not had time yet, but seen another BTCPay user have a bad gateway. problem,

**Comment by NicolasDorier** [comment]
> @Eskyee the RTL config path should be set to /data only, NOT /data/RTL.conf/RTL-Config.json.

@ShahanaFarooqui it happened to esky after an update to the docker container. The fact it is `/data/RTL.conf` is probably a bug in RTL.

Though it did not happened to me when I updated.

**Comment by ShahanaFarooqui** [comment]
@NicolasDorier This value is set through docker-compose, not within RTL. So docker config has to be updated to remove `/RTL.conf` from the path. 

However, as long as I remember, @Kukks updated it for BTC pay server users.

**Comment by NicolasDorier** [comment]
I see I think some users that updated at the wrong moment got their install corrupted because of the bug, and updating again does not fix the situation, requiring some ninja scripts to fix it.

**Comment by rockstardev** [comment]
@NicolasDorier it's double trouble, see my comment here... I just wasted 3 hours debugging this problem on newly launched instance: https://github.com/btcpayserver/btcpayserver-docker/issues/346#issuecomment-670230046

**Comment by saubyk** [comment]
This issue has been addressed with release v0.8.4 and host config is not created in the default config file.
