### ISSUE TITLE
npm ERR! rtl@0.12.0-beta postinstall: `ngcc`

### ISSUE THREAD

**Issue by manreo** [Ride-The-Lightning/RTL#919]
**Describe the bug**
Trying to install RTL 0.12.0
```
~/Downloads/RTL-0.12.0$ npm install --only=prod
.
.
.

> ngcc

/home/machine/Downloads/RTL-0.12.0/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:3
      import {createRequire as __cjsCompatRequire} from 'module';
             ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rtl@0.12.0-beta postinstall: `ngcc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rtl@0.12.0-beta postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by ShahanaFarooqui** [comment]
What are your NodeJS and npm versions?

**Comment by manreo** [comment]
probably too old, I've upgraded and it works. Thanks
